sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev --skip-lock"
  - "pipenv install coveralls --skip-lock"

script:
  - "pipenv run py.test --cov trefoil --cov-report term-missing"

after_success:
  - coveralls
